name: Daily commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Create and commit file
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require('fs');
          fs.writeFileSync('date.txt', new Date().toISOString());
          await github.rest.repos.createOrUpdateFileContents({
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: 'date.txt',
            message: 'Daily commit',
            content: Buffer.from(fs.readFileSync('date.txt')).toString('base64'),
            branch: 'main',
          });
