name: Daily commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup git
      run: |
        git config --global user.name 'GreggRoll'
        git config --global user.email 'adamsg_53@yahoo.com'

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup PAT
      run: |
        git remote set-url origin https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/GreggRoll/AutoCommit.git

    - name: Create and commit file
      run: |
        date >> date.txt
        git add date.txt
        git commit -m "Daily commit"
        git push
