name: Daily commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push
      run: |
        git config --global user.name 'GreggRoll'
        git config --global user.email 'adamsg_53@yahoo.com'
        date >> date.txt
        git add date.txt
        git commit -m "Daily commit"
        git push
